# Generated by Django 5.2.2 on 2025-07-09 03:41

import apps.main.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.cover_image_upload_path)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Journal Volume',
                'verbose_name_plural': 'Journal Volumes',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('authors', models.TextField(help_text='Comma-separated authors')),
                ('doi', models.URLField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=apps.main.models.article_pdf_upload_path)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=300)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.volume')),
            ],
            options={
                'ordering': ['volume', 'page_start'],
            },
        ),
    ]
