# Generated by Django 5.2.2 on 2025-07-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, help_text='Summary of the article'),
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, help_text='References or bibliography'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=500),
        ),
    ]
