# Generated by Django 5.2.2 on 2025-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_abstract_article_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.URLField(blank=True, help_text='Digital Object Identifier link for the article (if available).', null=True, verbose_name='DOI'),
        ),
    ]
